name: shop_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  permission_handler: ^11.0.0
  shared_preferences: ^2.0.15
  http: ^1.2.1
  pdf: ^3.6.0
  printing: ^5.0.0
  google_sign_in: ^5.2.4
  local_auth: ^2.1.3
  provider: ^6.0.0
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  screenshot: ^1.2.3
  path_provider: ^2.0.11
  url_launcher: ^6.0.0


  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  mysql1: 0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - google_fonts/
